language: cpp

git:
  depth: 3
  quiet: true

branches:
  only:
    - main

jobs:
  include:
    - name: "linux-gcc"
      os: linux
      arch: arm64
      dist: focal
      compiler: gcc
      before_install:
        - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
        - sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
        - sudo apt-get update
        - sudo apt-get install cmake
        - sudo apt-get install lcov googletest libgtest-dev 
      env:
        - BUILD="mkdir -p build && cd build && cmake --version && cmake .. && cmake --build . && ctest --output-on-failure -j 2"

script:
  - eval "${BUILD}"

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - locv --remove coverage.info '/usr/*' --output-file coverage.info
  - locv --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"


notifications:
  email:
    - cavallyb@gmail.com
