language: cpp

addons:
  apt:
    paclages:
      - lcov
      - googletest
      - libgtest-dev

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      name: "macOS-clang"
      env:
        - BUILD="mkdir -p build && cd build  && cmake .. && make -j2 && ctest --output-on-failure -j 2"

    - os: linux   
      dist: bionic
      compiler: gcc
      name: "linux-gcc"
      env:
        - BUILD="mkdir -p build && cd build  && cmake .. && make -j2 && ctest --output-on-failure -j 2"
      
before_install:
  - eval "${BEFORE_BUILD}"

script:
  - eval "${BUILD}"


after_sucess:
  - lcov --capture --directory . --output-file coverage.info
  - locv --remove coverage.info '/usr/*' --output-file coverage.info
  - locv --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"


notifications:
  email:
    - cavallyb@gmail.com
